// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for the `CreateIcebergCatalog` API.
public struct CreateIcebergCatalogRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this catalog will be created.
  /// Format: projects/{project_id}
  public var parent: Swift.String = Swift.String()

  /// Required. The name of the catalog.
  public var icebergCatalogId: Swift.String = Swift.String()

  /// Required. The catalog to create.
  /// The required fields for creation are:
  /// - catalog_type.
  /// Optionally: credential_mode can be provided, if Credential Vending is
  /// desired.
  public var icebergCatalog: IcebergCatalog? = nil

  /// Initialize a new instance of `CreateIcebergCatalogRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateIcebergCatalogRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case parent = "parent"
    case icebergCatalogId = "iceberg-catalog-id"
    case icebergCatalog = "icebergCatalog"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.icebergCatalogId = try container.decode(Swift.String.self, forKey: .icebergCatalogId)
    self.icebergCatalog = try container.decodeIfPresent(
      IcebergCatalog.self, forKey: .icebergCatalog)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.icebergCatalogId, forKey: .icebergCatalogId)
    try container.encode(self.icebergCatalog, forKey: .icebergCatalog)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.CreateIcebergCatalogRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
