// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for FailoverIcebergCatalog.
public struct FailoverIcebergCatalogRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the catalog in the form
  /// "projects/{project_id}/catalogs/{catalog_id}"
  public var name: Swift.String = Swift.String()

  /// Required. The region being assigned as the new primary replica region. For
  /// example "us-east1". This must be one of the replica regions in the
  /// catalog's list of replicas marked as a "secondary".
  public var primaryReplica: Swift.String = Swift.String()

  /// Optional. If set, only validate the request, but do not perform the update.
  /// This can be used to inspect the replication_time at any time, including
  /// before performing a fail-over.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. If unset, wait for all data from the source region to replicate
  /// to the new primary region before completing the failover, with no data loss
  /// (also called "soft failover"). If set, failover immediately, accepting the
  /// loss of any data committed in the source region after this timestamp, that
  /// has not yet replicated. If any data committed before this time has not
  /// replicated, the failover will not be performed and an error will be
  /// returned (also called "hard failover").
  public var conditionalFailoverReplicationTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `FailoverIcebergCatalogRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FailoverIcebergCatalogRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.FailoverIcebergCatalogRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
