// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol IcebergCatalogServiceStub {
    func getIcebergCatalogConfig(
      request: GetIcebergCatalogConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalogConfig

    func listIcebergNamespaces(
      request: ListIcebergNamespacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergNamespacesResponse

    func getIcebergNamespace(
      request: GetIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace

    func createIcebergNamespace(
      request: CreateIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace

    func deleteIcebergNamespace(
      request: DeleteIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func updateIcebergNamespace(
      request: UpdateIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse

    func listIcebergTableIdentifiers(
      request: ListIcebergTableIdentifiersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse

    func createIcebergTable(
      request: CreateIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func deleteIcebergTable(
      request: DeleteIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getIcebergTable(
      request: GetIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func loadIcebergTableCredentials(
      request: GetIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse

    func updateIcebergTable(
      request: UpdateIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func registerIcebergTable(
      request: RegisterIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func reportIcebergTableMetrics(
      request: ReportIcebergTableMetricsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getIcebergCatalog(
      request: GetIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog

    func listIcebergCatalogs(
      request: ListIcebergCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergCatalogsResponse

    func deleteIcebergCatalog(
      request: DeleteIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func updateIcebergCatalog(
      request: UpdateIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog

    func createIcebergCatalog(
      request: CreateIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog

    func failoverIcebergCatalog(
      request: FailoverIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse
  }

  class IcebergCatalogServiceTransport: IcebergCatalogServiceStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://biglake.googleapis.com")
    }

    public func getIcebergCatalogConfig(
      request: GetIcebergCatalogConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalogConfig {
      let path = try { () throws -> Swift.String in
        return "/iceberg/v1/restcatalog/v1/config"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.warehouse, prefix: "warehouse"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.IcebergCatalogConfig.self, from: data)
    }

    public func listIcebergNamespaces(
      request: ListIcebergNamespacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergNamespacesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.apiParent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.api_parent' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/namespaces"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.parent, prefix: "parent"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.ListIcebergNamespacesResponse.self, from: data)
    }

    public func getIcebergNamespace(
      request: GetIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.IcebergNamespace.self, from: data)
    }

    public func createIcebergNamespace(
      request: CreateIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/namespaces"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.icebergNamespace {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.IcebergNamespace.self, from: data)
    }

    public func deleteIcebergNamespace(
      request: DeleteIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func updateIcebergNamespace(
      request: UpdateIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/properties"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.icebergNamespaceUpdate {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse.self, from: data)
    }

    public func listIcebergTableIdentifiers(
      request: ListIcebergTableIdentifiersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/tables"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse.self, from: data)
    }

    public func createIcebergTable(
      request: CreateIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/tables"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleApi.HttpBody.self, from: data)
    }

    public func deleteIcebergTable(
      request: DeleteIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.purgeRequested, prefix: "purgeRequested"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func getIcebergTable(
      request: GetIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.snapshots, prefix: "snapshots"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleApi.HttpBody.self, from: data)
    }

    public func loadIcebergTableCredentials(
      request: GetIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/credentials"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.snapshots, prefix: "snapshots"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse.self, from: data)
    }

    public func updateIcebergTable(
      request: UpdateIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleApi.HttpBody.self, from: data)
    }

    public func registerIcebergTable(
      request: RegisterIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/register"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleApi.HttpBody.self, from: data)
    }

    public func reportIcebergTableMetrics(
      request: ReportIcebergTableMetricsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/v1/\(pathVariable0)/metrics"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      _ = try await self.inner.rpc(for: req).get()
    }

    public func getIcebergCatalog(
      request: GetIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/extensions/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.IcebergCatalog.self, from: data)
    }

    public func listIcebergCatalogs(
      request: ListIcebergCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergCatalogsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/extensions/\(pathVariable0)/catalogs"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "page-size"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "page-token"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.ListIcebergCatalogsResponse.self, from: data)
    }

    public func deleteIcebergCatalog(
      request: DeleteIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/extensions/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func updateIcebergCatalog(
      request: UpdateIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.icebergCatalog.map({ $0.name }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.iceberg_catalog.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/extensions/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.icebergCatalog {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.IcebergCatalog.self, from: data)
    }

    public func createIcebergCatalog(
      request: CreateIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/extensions/\(pathVariable0)/catalogs"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(
        contentsOf: try encoder.encode(request.icebergCatalogId, prefix: "iceberg-catalog-id"))
      query.append(
        contentsOf: try encoder.encode(request.primaryLocation, prefix: "primary_location"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.icebergCatalog {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.IcebergCatalog.self, from: data)
    }

    public func failoverIcebergCatalog(
      request: FailoverIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/iceberg/v1/restcatalog/extensions/\(pathVariable0):failover"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse.self, from: data)
    }
  }
}
