// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The Iceberg REST Catalog information.
public struct IcebergCatalog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The catalog name, `projects/my-project/catalogs/my-catalog`.
  /// This field is immutable.
  /// This field is ignored for CreateIcebergCatalog.
  public var name: Swift.String = Swift.String()

  /// Optional. The credential mode for the catalog.
  public var credentialMode: IcebergCatalog.CredentialMode = IcebergCatalog.CredentialMode()

  /// Output only. The service account used for credential vending, output only.
  /// Might be empty if Credential vending was never enabled for the catalog.
  public var biglakeServiceAccount: Swift.String = Swift.String()

  /// Required. The catalog type. Required for CreateIcebergCatalog.
  public var catalogType: IcebergCatalog.CatalogType = IcebergCatalog.CatalogType()

  /// Optional. The default location for the catalog. For the Google Cloud
  /// Storage Bucket catalog this is output only.
  public var defaultLocation: Swift.String = Swift.String()

  /// Output only. The GCP region(s) where the catalog metadata is stored.
  /// This will contain one value for all locations, except for the catalogs that
  /// are configured to use custom dual region buckets.
  public var catalogRegions: [Swift.String] = []

  /// Output only. When the catalog was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. When the catalog was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `IcebergCatalog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IcebergCatalog().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case credentialMode = "credential-mode"
    case biglakeServiceAccount = "biglake-service-account"
    case catalogType = "catalog-type"
    case defaultLocation = "default-location"
    case catalogRegions = "catalog-regions"
    case createTime = "create-time"
    case updateTime = "update-time"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.credentialMode = try container.decode(
      IcebergCatalog.CredentialMode.self, forKey: .credentialMode)
    self.biglakeServiceAccount = try container.decode(
      Swift.String.self, forKey: .biglakeServiceAccount)
    self.catalogType = try container.decode(IcebergCatalog.CatalogType.self, forKey: .catalogType)
    self.defaultLocation = try container.decode(Swift.String.self, forKey: .defaultLocation)
    self.catalogRegions = try container.decode([Swift.String].self, forKey: .catalogRegions)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.credentialMode, forKey: .credentialMode)
    try container.encode(self.biglakeServiceAccount, forKey: .biglakeServiceAccount)
    try container.encode(self.catalogType, forKey: .catalogType)
    try container.encode(self.defaultLocation, forKey: .defaultLocation)
    try container.encode(self.catalogRegions, forKey: .catalogRegions)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
  }

  /// Determines the catalog type.
  public enum CatalogType: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Catalog type for Google Cloud Storage Buckets.
    case gcsBucket
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .gcsBucket: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CATALOG_TYPE_UNSPECIFIED"
      case .gcsBucket: return "CATALOG_TYPE_GCS_BUCKET"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CATALOG_TYPE_UNSPECIFIED": self = .unspecified
      case "CATALOG_TYPE_GCS_BUCKET": self = .gcsBucket
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .gcsBucket
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .gcsBucket: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The credential mode used for the catalog.
  public enum CredentialMode: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// End user credentials, default. The authenticating user must have access
    /// to the catalog resources and the corresponding Google Cloud Storage
    /// files.
    case endUser
    /// Use credential vending. The authenticating user must have access to the
    /// catalog resources and the system will provide the caller with downscoped
    /// credentials to access the Google Cloud Storage files. All table
    /// operations in this mode would require `X-Iceberg-Access-Delegation`
    /// header with `vended-credentials` value included. System will generate a
    /// service account and the catalog administrator must grant the service
    /// account appropriate permissions.
    ///
    /// See:
    /// https://github.com/apache/iceberg/blob/931865ecaf40a827f9081dddb675bf1c95c05461/open-api/rest-catalog-open-api.yaml#L1854
    /// for more details.
    case vendedCredentials
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .endUser: return 1
      case .vendedCredentials: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CREDENTIAL_MODE_UNSPECIFIED"
      case .endUser: return "CREDENTIAL_MODE_END_USER"
      case .vendedCredentials: return "CREDENTIAL_MODE_VENDED_CREDENTIALS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CREDENTIAL_MODE_UNSPECIFIED": self = .unspecified
      case "CREDENTIAL_MODE_END_USER": self = .endUser
      case "CREDENTIAL_MODE_VENDED_CREDENTIALS": self = .vendedCredentials
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .endUser
      case 2: self = .vendedCredentials
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .endUser: return try container.encode(1)
      case .vendedCredentials: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.IcebergCatalog"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
