// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleWKT
import GoogleGax

extension Clients {
  protocol IcebergCatalogServiceStub: Sendable {
    func getIcebergCatalogConfig(
      request: GetIcebergCatalogConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalogConfig

    func listIcebergNamespaces(
      request: ListIcebergNamespacesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergNamespacesResponse

    func getIcebergNamespace(
      request: GetIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace

    func createIcebergNamespace(
      request: CreateIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace

    func deleteIcebergNamespace(
      request: DeleteIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws

    func updateIcebergNamespace(
      request: UpdateIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse

    func listIcebergTableIdentifiers(
      request: ListIcebergTableIdentifiersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse

    func createIcebergTable(
      request: CreateIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func deleteIcebergTable(
      request: DeleteIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws

    func getIcebergTable(
      request: GetIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func loadIcebergTableCredentials(
      request: GetIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse

    func updateIcebergTable(
      request: UpdateIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func registerIcebergTable(
      request: RegisterIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody

    func reportIcebergTableMetrics(
      request: ReportIcebergTableMetricsRequest, options: GoogleGax.RequestOptions
    ) async throws

    func getIcebergCatalog(
      request: GetIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog

    func listIcebergCatalogs(
      request: ListIcebergCatalogsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergCatalogsResponse

    func deleteIcebergCatalog(
      request: DeleteIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws

    func updateIcebergCatalog(
      request: UpdateIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog

    func createIcebergCatalog(
      request: CreateIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog

    func failoverIcebergCatalog(
      request: FailoverIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse
  }
}
