// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class IcebergCatalogServiceTransport: IcebergCatalogServiceStub {
    let inner: GoogleGax._HTTPClient

    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      self.inner = try GoogleGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://biglake.googleapis.com",
      )
    }

    public func getIcebergCatalogConfig(
      request: GetIcebergCatalogConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalogConfig {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          let path = "/iceberg/v1/restcatalog/v1/config"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.warehouse, prefix: "warehouse"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          paths.append(GoogleGax.PathMismatch())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBiglakeV1.IcebergCatalogConfig.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listIcebergNamespaces(
      request: ListIcebergNamespacesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergNamespacesResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.apiParent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              ],
              fieldName: "api_parent")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/namespaces"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.parent, prefix: "parent"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.apiParent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
            ],
            fieldName: "api_parent",
            expecting: "projects/*/catalogs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBiglakeV1.ListIcebergNamespacesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getIcebergNamespace(
      request: GetIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBiglakeV1.IcebergNamespace.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createIcebergNamespace(
      request: CreateIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/namespaces"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/catalogs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.icebergNamespace {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudBiglakeV1.IcebergNamespace.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteIcebergNamespace(
      request: DeleteIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateIcebergNamespace(
      request: UpdateIcebergNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/properties"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/properties"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.icebergNamespaceUpdate {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listIcebergTableIdentifiers(
      request: ListIcebergTableIdentifiersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/tables"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/catalogs/*/namespaces/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func createIcebergTable(
      request: CreateIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/tables"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["parent"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/catalogs/*/namespaces/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleApi.HttpBody.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteIcebergTable(
      request: DeleteIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.purgeRequested, prefix: "purgeRequested"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*/tables/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getIcebergTable(
      request: GetIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.snapshots, prefix: "snapshots"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*/tables/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleApi.HttpBody.self, timeout: options.attemptTimeout
      ).get()
    }

    public func loadIcebergTableCredentials(
      request: GetIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/credentials"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.snapshots, prefix: "snapshots"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*/tables/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func updateIcebergTable(
      request: UpdateIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*/tables/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleApi.HttpBody.self, timeout: options.attemptTimeout
      ).get()
    }

    public func registerIcebergTable(
      request: RegisterIcebergTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/register"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["parent"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/catalogs/*/namespaces/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleApi.HttpBody.self, timeout: options.attemptTimeout
      ).get()
    }

    public func reportIcebergTableMetrics(
      request: ReportIcebergTableMetricsRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
                .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/v1/\(pathVariable0)/metrics"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              .literal("/namespaces/"), .singleWildcard, .literal("/tables/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*/namespaces/*/tables/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getIcebergCatalog(
      request: GetIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/extensions/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBiglakeV1.IcebergCatalog.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listIcebergCatalogs(
      request: ListIcebergCatalogsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergCatalogsResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/extensions/\(pathVariable0)/catalogs"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "page-size"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "page-token"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudBiglakeV1.ListIcebergCatalogsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteIcebergCatalog(
      request: DeleteIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/extensions/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateIcebergCatalog(
      request: UpdateIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.icebergCatalog.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              ],
              fieldName: "iceberg_catalog.name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/extensions/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.icebergCatalog.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
            ],
            fieldName: "iceberg_catalog.name",
            expecting: "projects/*/catalogs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.icebergCatalog {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudBiglakeV1.IcebergCatalog.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createIcebergCatalog(
      request: CreateIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/extensions/\(pathVariable0)/catalogs"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(request.icebergCatalogId, prefix: "iceberg-catalog-id"))
          query.append(
            contentsOf: try encoder.encode(request.primaryLocation, prefix: "primary_location"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.icebergCatalog {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudBiglakeV1.IcebergCatalog.self, timeout: options.attemptTimeout
      ).get()
    }

    public func failoverIcebergCatalog(
      request: FailoverIcebergCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/iceberg/v1/restcatalog/extensions/\(pathVariable0):failover"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/catalogs/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/catalogs/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
