// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The iceberg catalog configuration.
public struct IcebergCatalogConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Properties that should be used to override client
  /// configuration; applied after defaults and client configuration. Required,
  /// even if empty.
  public var overrides: [Swift.String: Swift.String] = [:]

  /// Output only. Properties that should be used as default configuration;
  /// applied before client configuration. Required, even if empty.
  public var defaults: [Swift.String: Swift.String] = [:]

  /// Output only. Endpoints, required, must not be empty.
  public var endpoints: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `IcebergCatalogConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IcebergCatalogConfig().with { $0.overrides = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let overrides = CodingKeys(stringValue: "overrides")
    static let defaults = CodingKeys(stringValue: "defaults")
    static let endpoints = CodingKeys(stringValue: "endpoints")

    static let _knownKeys: Set<Swift.String> = [
      "overrides",
      "defaults",
      "endpoints",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .overrides)
    {
      self.overrides = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .defaults)
    {
      self.defaults = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .endpoints) {
      self.endpoints = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.overrides, forKey: .overrides)
    try container.encode(self.defaults, forKey: .defaults)
    try container.encode(self.endpoints, forKey: .endpoints)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.IcebergCatalogConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
