// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class IcebergCatalogServiceLogging: IcebergCatalogServiceStub {
    let inner: any IcebergCatalogServiceStub
    let logger: Logger

    public init(_ inner: any IcebergCatalogServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-biglake-v1"
      logger[metadataKey: "gcp.client.service"] = "biglake"
      logger[metadataKey: "gcp.experimental.swift.client"] = "IcebergCatalogService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getIcebergCatalogConfig(
      request: GetIcebergCatalogConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalogConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIcebergCatalogConfig",
        action: {
          (r: GetIcebergCatalogConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.IcebergCatalogConfig
          in
          return try await self.inner.getIcebergCatalogConfig(request: r, options: o)
        })
    }

    public func listIcebergNamespaces(
      request: ListIcebergNamespacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergNamespacesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIcebergNamespaces",
        action: {
          (r: ListIcebergNamespacesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.ListIcebergNamespacesResponse
          in
          return try await self.inner.listIcebergNamespaces(request: r, options: o)
        })
    }

    public func getIcebergNamespace(
      request: GetIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIcebergNamespace",
        action: {
          (r: GetIcebergNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.IcebergNamespace
          in
          return try await self.inner.getIcebergNamespace(request: r, options: o)
        })
    }

    public func createIcebergNamespace(
      request: CreateIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergNamespace {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIcebergNamespace",
        action: {
          (r: CreateIcebergNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.IcebergNamespace
          in
          return try await self.inner.createIcebergNamespace(request: r, options: o)
        })
    }

    public func deleteIcebergNamespace(
      request: DeleteIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIcebergNamespace",
        action: {
          (r: DeleteIcebergNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteIcebergNamespace(request: r, options: o)
        })
    }

    public func updateIcebergNamespace(
      request: UpdateIcebergNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIcebergNamespace",
        action: {
          (r: UpdateIcebergNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.UpdateIcebergNamespaceResponse
          in
          return try await self.inner.updateIcebergNamespace(request: r, options: o)
        })
    }

    public func listIcebergTableIdentifiers(
      request: ListIcebergTableIdentifiersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIcebergTableIdentifiers",
        action: {
          (r: ListIcebergTableIdentifiersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.ListIcebergTableIdentifiersResponse
          in
          return try await self.inner.listIcebergTableIdentifiers(request: r, options: o)
        })
    }

    public func createIcebergTable(
      request: CreateIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIcebergTable",
        action: {
          (r: CreateIcebergTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.createIcebergTable(request: r, options: o)
        })
    }

    public func deleteIcebergTable(
      request: DeleteIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIcebergTable",
        action: {
          (r: DeleteIcebergTableRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteIcebergTable(request: r, options: o)
        })
    }

    public func getIcebergTable(
      request: GetIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIcebergTable",
        action: {
          (r: GetIcebergTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.getIcebergTable(request: r, options: o)
        })
    }

    public func loadIcebergTableCredentials(
      request: GetIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "loadIcebergTableCredentials",
        action: {
          (r: GetIcebergTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.LoadIcebergTableCredentialsResponse
          in
          return try await self.inner.loadIcebergTableCredentials(request: r, options: o)
        })
    }

    public func updateIcebergTable(
      request: UpdateIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIcebergTable",
        action: {
          (r: UpdateIcebergTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.updateIcebergTable(request: r, options: o)
        })
    }

    public func registerIcebergTable(
      request: RegisterIcebergTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.HttpBody {
      try await self._intercept(
        request: request,
        options: options,
        name: "registerIcebergTable",
        action: {
          (r: RegisterIcebergTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApi.HttpBody
          in
          return try await self.inner.registerIcebergTable(request: r, options: o)
        })
    }

    public func reportIcebergTableMetrics(
      request: ReportIcebergTableMetricsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "reportIcebergTableMetrics",
        action: {
          (r: ReportIcebergTableMetricsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.reportIcebergTableMetrics(request: r, options: o)
        })
    }

    public func getIcebergCatalog(
      request: GetIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIcebergCatalog",
        action: {
          (r: GetIcebergCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.IcebergCatalog
          in
          return try await self.inner.getIcebergCatalog(request: r, options: o)
        })
    }

    public func listIcebergCatalogs(
      request: ListIcebergCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.ListIcebergCatalogsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIcebergCatalogs",
        action: {
          (r: ListIcebergCatalogsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.ListIcebergCatalogsResponse
          in
          return try await self.inner.listIcebergCatalogs(request: r, options: o)
        })
    }

    public func deleteIcebergCatalog(
      request: DeleteIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIcebergCatalog",
        action: {
          (r: DeleteIcebergCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteIcebergCatalog(request: r, options: o)
        })
    }

    public func updateIcebergCatalog(
      request: UpdateIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIcebergCatalog",
        action: {
          (r: UpdateIcebergCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.IcebergCatalog
          in
          return try await self.inner.updateIcebergCatalog(request: r, options: o)
        })
    }

    public func createIcebergCatalog(
      request: CreateIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.IcebergCatalog {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIcebergCatalog",
        action: {
          (r: CreateIcebergCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.IcebergCatalog
          in
          return try await self.inner.createIcebergCatalog(request: r, options: o)
        })
    }

    public func failoverIcebergCatalog(
      request: FailoverIcebergCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "failoverIcebergCatalog",
        action: {
          (r: FailoverIcebergCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBiglakeV1.FailoverIcebergCatalogResponse
          in
          return try await self.inner.failoverIcebergCatalog(request: r, options: o)
        })
    }
  }
}
