// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The response message for the `ListIcebergNamespaces` API.
public struct ListIcebergNamespacesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The list of namespaces.
  public var namespaces: [GoogleCloudWkt.ListValue] = []

  /// The next page token for pagination.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListIcebergNamespacesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListIcebergNamespacesResponse().with { $0.namespaces = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case namespaces = "namespaces"
    case nextPageToken = "next-page-token"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.namespaces = try container.decode([GoogleCloudWkt.ListValue].self, forKey: .namespaces)
    self.nextPageToken = try container.decode(Swift.String.self, forKey: .nextPageToken)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.namespaces, forKey: .namespaces)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.biglake.v1.ListIcebergNamespacesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
