// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request message for the `ListIcebergCatalogs` API.
public struct ListIcebergCatalogsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this catalog will be created.
  /// Format: projects/{project_id}
  public var parent: Swift.String = Swift.String()

  /// Optional. The view of the catalog to return.
  public var view: ListIcebergCatalogsRequest.CatalogView = ListIcebergCatalogsRequest.CatalogView()

  /// Optional. The maximum number of catalogs to return. The service may return
  /// fewer than this value.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token, received from a previous `ListIcebergCatalogs`
  /// call. Provide this to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The filter expression.
  /// The only parameter currently supported is filtering based on the
  /// `IcebergCatalog.catalog_type` field.
  ///
  /// Examples:
  /// * `catalog_type = CATALOG_TYPE_BIGLAKE`
  /// * `catalog_type != CATALOG_TYPE_GCS_BUCKET`
  /// * `catalog_type = CATALOG_TYPE_BIGLAKE OR catalog_type =
  /// CATALOG_TYPE_GCS_BUCKET`
  /// * `NOT catalog_type = CATALOG_TYPE_GCS_BUCKET`
  public var filter: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListIcebergCatalogsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListIcebergCatalogsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let view = CodingKeys(stringValue: "view")
    static let pageSize = CodingKeys(stringValue: "page-size")
    static let pageToken = CodingKeys(stringValue: "page-token")
    static let filter = CodingKeys(stringValue: "filter")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "view",
      "page-size",
      "page-token",
      "filter",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(
      ListIcebergCatalogsRequest.CatalogView.self, forKey: .view)
    {
      self.view = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.view, forKey: .view)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.filter, forKey: .filter)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The enumeration of the views that can be returned.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CatalogView: Codable, Equatable, Sendable {
    /// Default/unset value. Same as BASIC.
    case unspecified
    /// Include only the name and catalog type.
    case basic
    /// Include all fields of the catalog.
    case full
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .basic: return 1
      case .full: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CATALOG_VIEW_UNSPECIFIED"
      case .basic: return "CATALOG_VIEW_BASIC"
      case .full: return "CATALOG_VIEW_FULL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CatalogView/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CATALOG_VIEW_UNSPECIFIED": self = .unspecified
      case "CATALOG_VIEW_BASIC": self = .basic
      case "CATALOG_VIEW_FULL": self = .full
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CatalogView/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .basic
      case 2: self = .full
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CATALOG_VIEW_UNSPECIFIED")
      case .basic: return try container.encode("CATALOG_VIEW_BASIC")
      case .full: return try container.encode("CATALOG_VIEW_FULL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.ListIcebergCatalogsRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
