// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ListIcebergNamespacesRequest
public struct ListIcebergNamespacesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. PageToken
  public var pageToken: Swift.String = Swift.String()

  /// Optional. For servers that support pagination, this signals an upper bound
  /// of the number of results that a client will receive. For servers that do
  /// not support pagination, clients may receive results larger than the
  /// indicated `pageSize`.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Required. The parent from the resource path.
  public var apiParent: Swift.String = Swift.String()

  /// Optional. An optional namespace, underneath which to list namespaces. If
  /// not provided or empty, all top-level namespaces should be listed. If parent
  /// is a multipart namespace, the parts must be separated by the unit separator
  /// (`0x1F`) byte.
  /// Not a real parent, so ST_NOT_REQUIRED.
  public var parent: Swift.String = Swift.String()

  /// Initialize a new instance of `ListIcebergNamespacesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListIcebergNamespacesRequest().with { $0.pageToken = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.biglake.v1.ListIcebergNamespacesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
