// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ListIcebergNamespacesRequest
public struct ListIcebergNamespacesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Specify the page_token returned in the previous response to
  /// retrieve the next page of results.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. For servers that support pagination, this signals an upper bound
  /// of the number of results that a client will receive. For servers that do
  /// not support pagination, clients may receive results larger than the
  /// indicated `pageSize`. Defaults to 100 if not set.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Required. The parent from the resource path.
  public var apiParent: Swift.String = Swift.String()

  /// Optional. An optional namespace, underneath which to list namespaces. If
  /// not provided or empty, all top-level namespaces should be listed. If parent
  /// is a multipart namespace, the parts must be separated by the unit separator
  /// (`0x1F`) byte.
  /// Not a real parent, so ST_NOT_REQUIRED.
  public var parent: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListIcebergNamespacesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListIcebergNamespacesRequest().with { $0.pageToken = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let apiParent = CodingKeys(stringValue: "apiParent")
    static let parent = CodingKeys(stringValue: "parent")

    static let _knownKeys: Set<Swift.String> = [
      "pageToken",
      "pageSize",
      "apiParent",
      "parent",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiParent) {
      self.apiParent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.apiParent, forKey: .apiParent)
    try container.encode(self.parent, forKey: .parent)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.ListIcebergNamespacesRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
