// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The response message for the `ListIcebergCatalogs` API.
public struct ListIcebergCatalogsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The list of iceberg catalogs.
  public var icebergCatalogs: [IcebergCatalog] = []

  /// Output only. The next page token for pagination.
  public var nextPageToken: Swift.String = Swift.String()

  /// Output only. The list of unreachable cloud regions. If non-empty, the
  /// result set might be incomplete.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `ListIcebergCatalogsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListIcebergCatalogsResponse().with { $0.icebergCatalogs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case icebergCatalogs = "iceberg-catalogs"
    case nextPageToken = "next-page-token"
    case unreachable = "unreachable"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.icebergCatalogs = try container.decode([IcebergCatalog].self, forKey: .icebergCatalogs)
    self.nextPageToken = try container.decode(Swift.String.self, forKey: .nextPageToken)
    self.unreachable = try container.decode([Swift.String].self, forKey: .unreachable)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.icebergCatalogs, forKey: .icebergCatalogs)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.unreachable, forKey: .unreachable)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.ListIcebergCatalogsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
