// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request message for the `RegisterIcebergTable` API.
public struct RegisterIcebergTableRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Table to register in the format:
  /// `projects/{project_id}/catalogs/{catalog_id}/namespaces/{namespace}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The name of the table to register.
  public var name: Swift.String = Swift.String()

  /// Required. The metadata location of the table.
  public var metadataLocation: Swift.String = Swift.String()

  /// Optional. Whether to overwrite the table if it already exists. Default is
  /// false.
  public var overwrite: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `RegisterIcebergTableRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RegisterIcebergTableRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case parent = "parent"
    case name = "name"
    case metadataLocation = "metadata-location"
    case overwrite = "overwrite"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.metadataLocation = try container.decode(Swift.String.self, forKey: .metadataLocation)
    self.overwrite = try container.decode(Swift.Bool.self, forKey: .overwrite)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.metadataLocation, forKey: .metadataLocation)
    try container.encode(self.overwrite, forKey: .overwrite)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.RegisterIcebergTableRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
