// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The storage credential for a path in the table.
public struct StorageCredential: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Indicates a storage location prefix where the credential is relevant.
  public var `prefix`: Swift.String = Swift.String()

  /// The credentials for the storage location. The keys that are populated are:
  /// - `gcs.oauth2.token`
  /// - `gcs.oauth2.token_expires_at`
  /// - `expiration-time` (to support federation from Polaris).
  public var config: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `StorageCredential`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageCredential().with { $0.`prefix` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `prefix` = "prefix"
    case config = "config"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`prefix` = try container.decode(Swift.String.self, forKey: .`prefix`)
    self.config = try container.decode([Swift.String: Swift.String].self, forKey: .config)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`prefix`, forKey: .`prefix`)
    try container.encode(self.config, forKey: .config)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.StorageCredential"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
