// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The response message for the `UpdateIcebergNamespace` API.
public struct UpdateIcebergNamespaceResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. List of properties that were removed.
  public var removed: [Swift.String] = []

  /// Output only. List of properties that were added or updated.
  public var updated: [Swift.String] = []

  /// Output only. List of properties that were requested to be removed, but were
  /// not found.
  public var missing: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateIcebergNamespaceResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateIcebergNamespaceResponse().with { $0.removed = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let removed = CodingKeys(stringValue: "removed")
    static let updated = CodingKeys(stringValue: "added")
    static let missing = CodingKeys(stringValue: "missing")

    static let _knownKeys: Set<Swift.String> = [
      "removed",
      "added",
      "missing",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .removed) {
      self.removed = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .updated) {
      self.updated = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .missing) {
      self.missing = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.removed, forKey: .removed)
    try container.encode(self.updated, forKey: .updated)
    try container.encode(self.missing, forKey: .missing)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.biglake.v1.UpdateIcebergNamespaceResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
